lerobot_data_bridge:
  ros__parameters:
    sample_rate_hz: 15.0
    max_data_age_sec: 1.0
    publish_host: "127.0.0.1"
    publish_port: 5555
    command_host: "127.0.0.1"
    command_port: 5556
    command_max_age_sec: 0.5
    task_name: "pick and place"
    deployment_mode: true
    deployment_start_active: false
    deployment_hold_warmup_sec: 1.0
    deployment_hold_stability_tolerance: 0.002
    deployment_state_source: "topics"
    left_robot_ip: "172.16.0.3"
    right_robot_ip: "172.16.0.2"
    deployment_gripper_action_value: 0.0
    include_gripper: true
    include_right_arm: true
    require_gripper_freshness: true
    arm_action_source: "robot_state"
    left_robot_joint_state_topic: "/left/franka/joint_states"
    right_robot_joint_state_topic: "/right/franka/joint_states"
    left_robot_gripper_state_topic: "/left/franka_gripper/joint_states"
    right_robot_gripper_state_topic: "/right/franka_gripper/joint_states"
    left_deployment_gripper_command_topic: "/left/gripper/gripper_client/target_gripper_width_percent"
    right_deployment_gripper_command_topic: "/right/gripper/gripper_client/target_gripper_width_percent"
    left_deployment_joint_command_topic: "/left/deployment/joint_states"
    right_deployment_joint_command_topic: "/right/deployment/joint_states"
    left_deployment_enable_service: "/left/deployment_joint_impedance_controller/set_deployment_enabled"
    right_deployment_enable_service: "/right/deployment_joint_impedance_controller/set_deployment_enabled"

    camera_1_enabled: true
    camera_1_name: "cam_left"
    camera_1_topic: "/cameras/cam_left/image_raw"
    camera_2_enabled: true
    camera_2_name: "cam_front"
    camera_2_topic: "/cameras/cam_front/image_raw"
    camera_3_enabled: true
    camera_3_name: "cam_right"
    camera_3_topic: "/cameras/cam_right/image_raw"
